#!/bin/bash
openssl req -new -sha256 -nodes -out ./cert/server.csr -newkey rsa:4096 -keyout ./private/server.key -config ./server.csr.conf
openssl x509 -req -in ./cert/server.csr -CA ./cert/rootCA.pem -CAkey ./private/rootCA.key -CAcreateserial -out ./cert/server.crt -days 3650 -sha256 -extfile v3.ext -trustout
